---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hook-rbac.yaml
  - ./cluster17.yaml
  - ./cluster18.yaml
  - ./database-autoposter.yaml
  - ./database-stalwart.yaml
  - ./external-secret-stalwart.yaml
  - ./secret-autoposter-user.sops.yaml
  - ./gatus.yaml
  - ./objectstore.yaml
  - ./objectstore18.yaml
  - ./prometheusrule.yaml
  - ./scheduledbackup.yaml
  - ./scheduledbackup18.yaml
  - ./service.yaml
