apiVersion: v1
kind: Secret
metadata:
  name: postgres18-autoposter-user
  namespace: database
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:K840G7Z8bVNkhQ==,iv:TXMz/pZwObxTuigJ0UYmhJ5vqOkwulVphIQi5wrL69s=,tag:mKvO1Jdhh+ehT7446e3ndg==,type:str]
  password: ENC[AES256_GCM,data:Mcdnt6q1y8oJa1M4mdDfd6y/XSSo4SjRnvaXawmZl5D807BKTsRMAcKeVLF3J4SA,iv:1gPW564dfpiXqt1hYbz2J1hR20qNCXfxrUDds7DKPik=,tag:/EN4Y2WNzrw9KnZgZyCguQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbWJuM1NhOTc5Ujh1QzlN
        YnA4bWExUzYvMlZWVGpBZ24ycVlKNm9wM0JNCmROTWcyTFFYdjFoQjI1L3pnSFow
        bFQvYTQ1MGt1WHlaUENUdm0rVHlsYk0KLS0tIG1aWVZ4TTRaYXZ4emJkNWhsME4r
        K2tnVnhCRHdGZGhuaUJ4UmZ2UFkvWDQKFkjobrSS9uWtHz3BZb2epz8AbU6ZGk2X
        uSPnIOQ5QxW6NK+aAno+2Q+NqmgfJUOCRdVtOfvu9Qww9V8vPJ6BSg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T21:12:35Z"
  mac: ENC[AES256_GCM,data:MFPtV7G0WqwSzg00/6vhLknRBxmBo9wkrAT0hTUH/YQDHfdnNPA0e2FYPz8/njo6crBWxSOaxWxD9JssgYaJGgcmBIhWx3mq45a/kbIIzwRZQ6LEwcItGm2qdL6EOIfhmT36ORW+2Jn6vt705UgJ6uiGaU3Uo86G/CwBh2FPKRA=,iv:aGYlUJqYfy7q8SGsGPjROgyN/Jg4c5FYn/opMta/WdE=,tag:haIK5DxGrMZZCiCEMjU+HA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
