apiVersion: v1
kind: Secret
metadata:
    name: technitium-secret
    namespace: network
stringData:
    DNS_SERVER_DOMAIN: ENC[AES256_GCM,data:/4/gmvvHWC9raB0=,iv:u2kTefasxYNntBD2ALdPJV6FDHK7BnHQ3rkx4aerCtI=,tag:Z8hvAgj9GO1Aql+EA8Kk/g==,type:str]
    DNS_SERVER_ADMIN_PASSWORD: ENC[AES256_GCM,data:yoTjfubBwkw8HbPCDMytMA==,iv:rvIHYQAQfA4O/xoNdBuBTa3jzGCJsadbWIMZnxz40jg=,tag:HD5lKFCrD2RrlBR7teaHbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S0x3cXcwT2xTc0NXdTZu
            UUVkVmthb3U3dWJPL1lJTkVrOVNuZG4wMUY0Cm1PT2xWTWhVallSeWdNKzk2SXpz
            eGNJcU5DTElHclhleUdiR0ExdlI5d1kKLS0tIGNabnJzK29Jb3ZYblRZVDBpbGRT
            WGdaTk1JcWdKbTZzMDBqb3Eyc0ZEanMK17/MKbmneZnnvVkuB6o5I2qQ+cdBlw2/
            6HrgU7S6u5XuinioMMOsNO1pIQgMTrvxNBQJXCzj4wL7A6W/M2d8TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T18:44:35Z"
    mac: ENC[AES256_GCM,data:8SSqMxeKfVRN2kiFbdh3DihrdfijLM721tcNNnbcJymLX9Xl/e483KrUOlOWFvGGJGGEXBF2lWNuPjdZjdtcwttR0Dhel/2wiqRKD6ZaBzsnxHZ/jr60z/hCKKNYCZGezuI76im0Qo44tqzHlg0qbMAWmTgto5fEiqE/2k1SBeU=,iv:BZ7y7AwmbcpnJR6gsOkvo4hhfKSQuHBs19BSwElW56g=,tag:Qfaa1QdnPIfq0uBinOxaCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
