---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./namespace.yaml
  - ./autoposter/ks.yaml
  - ./bazarr/ks.yaml
  - ./configarr/ks.yaml
  - ./kometa/ks.yaml
  - ./maintainerr/ks.yaml
  - ./posterizarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./seerr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./spotarr/ks.yaml
  - ./taggarr/ks.yaml
  - ./tautulli/ks.yaml
  - ./tracearr/ks.yaml
  - ./wizarr/ks.yaml
components:
  - ../../components/common
