---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: seerr
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      seerr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/seerr-team/seerr
              tag: v3.4.0
            env:
              TZ: Europe/Helsinki
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 5055
                  initialDelaySeconds: 20
                  periodSeconds: 15
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 5055
                  initialDelaySeconds: 60
                  periodSeconds: 15
                  timeoutSeconds: 3
              startup:
                enabled: true
                spec:
                  httpGet:
                    path: /
                    port: 5055
                  failureThreshold: 60
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 15m
                memory: 512Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
      dnsConfig:
        options:
          - name: ndots
            value: "1"
          - name: use-vc
          - name: single-request-reopen
    service:
      app:
        controller: seerr
        ports:
          http:
            port: 5055
    persistence:
      config:
        existingClaim: seerr
        globalMounts:
          - path: /app/config
