---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - rbac.yaml
  - pvc.yaml
  - secret.sops.yaml

configMapGenerator:
  - name: forgejo-runner-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
  - name: forgejo-runner-config
    files:
      - config.yaml
    options:
      disableNameSuffixHash: true
