---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-auth
spec:
  plugin:
    traefik-oidc-auth:
      LogLevel: WARN
      Secret: "${OIDC_ENCRYPTION_SECRET}"
      BypassAuthenticationRule: >-
        PathPrefix(`/api`)
        || PathPrefix(`/newznab`)
        || PathPrefix(`/identity`)
        || PathPrefix(`/triggers`)
        || PathPrefix(`/meshagents`)
        || PathPrefix(`/meshsettings`)
        || PathPrefix(`/agent`)
        || PathPrefix(`/control`)
        || PathPrefix(`/meshrelay`)
        || PathPrefix(`/wl`)
        || PathPrefix(`/socket.io`)
        || PathPrefix(`/audiobookshelf/socket.io`)
        || PathPrefix(`/signalr`)
      Provider:
        Url: "https://auth.vaderrp.com/application/o/traefik/"
        ClientId: "${OIDC_CLIENT_ID}"
        ClientSecret: "${OIDC_CLIENT_SECRET}"
      Scopes: ["openid", "profile", "email"]
      CallbackUri: "/oidc/callback"
      Headers:
        - Name: X-Authentik-Username
          Value: "{{ .claims.preferred_username }}"
        - Name: X-Authentik-Email
          Value: "{{ .claims.email }}"
        - Name: X-Authentik-Name
          Value: "{{ .claims.name }}"
        - Name: X-Authentik-Groups
          Value: "{{ .claims.groups }}"
