---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ruoka
resources:
  - namespace.yaml
  - ./ruoka/ks.yaml
  - ./ruoka-admin/ks.yaml
components:
  - ../../components/common
