---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    goldilocks.fairwinds.com/vpa-update-mode: "auto"
    goldilocks.fairwinds.com/enabled: "true"
