---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: hietamakidojo
  namespace: hietamakidojo
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "5m"
    fluxcd.controlplane.io/reconcileTimeout: "10m"
spec:
  inputsFrom:
    - kind: ResourceSetInputProvider
      name: hietamakidojo-branches
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: hietamakidojo-<< inputs.branch >>
        namespace: hietamakidojo
      spec:
        interval: 1m
        url: https://forgejo.vaderrp.com/operinko-labs/hietamakidojo.git
        ref:
          branch: << inputs.branch >>
        secretRef:
          name: hietamakidojo-forgejo-pat

    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: hietamakidojo-<< inputs.branch >>
        namespace: hietamakidojo
      spec:
        interval: 5m
        prune: true
        wait: true
        timeout: 5m
        force: true
        decryption:
          provider: sops
        sourceRef:
          kind: GitRepository
          name: hietamakidojo-<< inputs.branch >>
        path: ./deploy/k8s/overlays/<< inputs.branch >>
