---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  labels:
    argocd.argoproj.io/managed-by: argocd
    goldilocks.fairwinds.com/vpa-update-mode: "auto"
    goldilocks.fairwinds.com/enabled: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    goldilocks.fairwinds.com/vpa-resource-policy: |
      {
        "containerPolicies": [
          {
            "containerName": "dragonfly",
            "minAllowed": {
              "memory": "512Mi"
            }
          }
        ]
      }

