---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-secret
  namespace: observability
spec:
  refreshInterval: 1h
  target:
    name: gatus-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        NTFY_TOKEN: "{{ .ntfy_token }}"
  data:
    - secretKey: ntfy_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3a7ed3e8-9158-491b-a0c1-25a7b95ef26a
        property: ntfy_token
