---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tainer
  namespace: tools
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tainer
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      tainer:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: tainersh/tainer
              tag: 1.3.2
            env:
              TZ: Europe/Helsinki
              APP_URL: https://tainer.vaderrp.com
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 3000
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 512Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        controller: tainer
        ports:
          http:
            port: *port

    persistence:
      data:
        existingClaim: tainer
        advancedMounts:
          tainer:
            app:
              - path: /app/data
