---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  labels:
    pod-security.kubernetes.io/enforce: privileged
    goldilocks.fairwinds.com/vpa-update-mode: "auto"
    goldilocks.fairwinds.com/enabled: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    goldilocks.fairwinds.com/vpa-resource-policy: |
      {
        "containerPolicies": [
          {
            "containerName": "server",
            "controlledValues": "RequestsOnly"
          },
          {
            "containerName": "worker",
            "controlledValues": "RequestsOnly"
          }
        ]
      }

