---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - httproute.yaml
  - external-secret.yaml
  - dnsendpoint.yaml
  - configmap.yaml
  - webui-job.yaml
configMapGenerator:
  - name: stalwart-loki-rules
    files:
      - stalwart.yaml=./lokirule.yaml
    options:
      labels:
        loki_rule: "true"
generatorOptions:
  disableNameSuffixHash: true
