---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/fluxcd.controlplane.io/resourcesetinputprovider_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: ruoka-admin-branches
  namespace: ruoka
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "1m"
spec:
  type: GitHubBranch
  url: https://github.com/operinko-labs/ruoka-admin
  filter:
    includeBranch: "^main$"
  secretRef:
    name: ruoka-admin-github-pat
