---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/fluxcd.controlplane.io/resourcesetinputprovider_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: ruskonkesateatteri-branches
  namespace: ruskonkesateatteri
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "1m"
spec:
  type: GiteaBranch
  url: https://forgejo.vaderrp.com/operinko-labs/ruskonkesateatteri
  filter:
    includeBranch: "^main$"
  secretRef:
    name: ruskonkesateatteri-forgejo-pat
