---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-oidc-secret
  namespace: network
spec:
  refreshInterval: 1h
  target:
    name: traefik-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6a906531-de3f-4dd3-a957-919cafbfd2f1
        property: username
    - secretKey: OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6a906531-de3f-4dd3-a957-919cafbfd2f1
        property: password
    - secretKey: OIDC_ENCRYPTION_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 6a906531-de3f-4dd3-a957-919cafbfd2f1
        property: OIDC_ENCRYPTION_SECRET
