apiVersion: v1
kind: Secret
metadata:
    name: traefik-crowdsec-bouncer
    namespace: network
stringData:
    lapi_key: ENC[AES256_GCM,data:N4bPACqGWHGsP0D85hfJsdHHMlR3Krpm2zgNE/Cp2E76w2KE3uJ3fxOnYg==,iv:X7sAnf9iSeldT2+ffhVBcTMWb+Ee69kmYV7CQwZDqTg=,tag:5vafsCVrRFWY63aZtCcsSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSGNPUForbXI4VFduOXZH
            UlMwV1I2TWlFOEpUcmtsQklHeUMwN3JVbTJ3CmF5UHY4eXNqcHppR1JWZjIxakRX
            ZkFsZjhRbG1HSDlpMVNIRmdDdFJRb2sKLS0tIDVjSEFQY0grbnRWV2V5UU5BVjgx
            VDR5dXZ5V0hSdmNSeVJPNFdsQmxKeDgKNgsLi4Y/pHsJCZrb3USFXJVEHEnRGN8E
            2NH1sxrP+gWMFPjsLu3+jiQ4ISZKj770cGeIo3Cs1Yc4tnrWOS/6nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T18:44:56Z"
    mac: ENC[AES256_GCM,data:bl3iK529muz68ePOlcZBRRIvBqk++X8dVeRuBiCSp24+HHvU+ADWFasiFPYa48Ak66inKRzSy5pYYPG16TUZ8ewOsNZnPnuChINzu8C6GJdSW4Sjvrn2Wq+ZmN3VHXRBLjypff4kPO1lvs9vzgh9yHm4Gi45FaxbDlcHengFVVc=,iv:mcUr5XAHXmeq3G5yIIWBMqhYlmiD0OpAjCXnJMk2itM=,tag:wQgI8zg73//Z1T/WNi14Cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
