---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-gdrive-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: minio-gdrive-sync
    creationPolicy: Owner
  data:
    - secretKey: ENCRYPTION_PASSWORD
      remoteRef:
        key: 980055b1-e67e-43b3-8634-87545f4cce16
        property: encryption_password
    - secretKey: ENCRYPTION_SALT
      remoteRef:
        key: 980055b1-e67e-43b3-8634-87545f4cce16
        property: encryption_salt
    - secretKey: GDRIVE_TOKEN
      remoteRef:
        key: 980055b1-e67e-43b3-8634-87545f4cce16
        property: gdrive_token
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: ed32aa71-d74b-43bc-a467-aaa2569f532f
        property: aws-access-key-id
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: ed32aa71-d74b-43bc-a467-aaa2569f532f
        property: aws-secret-access-key
