apiVersion: v1
kind: Secret
metadata:
  name: autoposter-sops
  namespace: media
type: Opaque
stringData:
  AUTOPOSTER_DATABASE_URL: ENC[AES256_GCM,data:Va1taKhUhb/osuVnBs7dXl6Y2kPTboTrefZ7Kjgvd+u+UZgtGB0A4bo+hIQCpPuFpUeiH3MZTb0mOMgpqBetw3alhCC4ccDLWacAyg8jZtgr8/vubfu7Q9JQ4cg2d88NL9WtDYvQXj8QuWVWRGHofnyDQDP8dCjf/6uGen0DEQh/SxS87NHQau0=,iv:l1Kru+gdvRQrTPI1zJIyGQV4T0pMyF6rrvGAh/GKaos=,tag:5MflpcQe9Tzsl/B/eiunEQ==,type:str]
  AUTOPOSTER_WEBHOOK_SECRET: ENC[AES256_GCM,data:lVlmEQi0r0zMsP74E4nbollmf0/uZggXCxw7ke75tcbY4p5MfNl07EbY/QSRrqSiE3dbrPsJpWkrG98g0VIwbA==,iv:2X1vlcfMX+gPE73pOo5a3IAXZs6tpKwY2x/ONuy3Dbs=,tag:rjUd38FWp58owmeWv/FeMg==,type:str]
  AUTOPOSTER_ADMIN_PASSWORD_HASH: ENC[AES256_GCM,data:AX7k8Uipj2N3562t+Cv+hbATbJ39vlFKdTQZjf9FQrqArCfv2l4ksBYs/oQFb+K7Xl7BVW1ZkBkTifhr,iv:w1w30jLrdsMvmznmOJ4PjEhzUPq88fl8sLUZNPtXx3o=,tag:0TKcijq+nbmT0icjgv3L1g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SUt3ZXFzM21nS1E2eGRL
        U3lmMnI5VlpUN0hmSzA4dDZBYjkraVF1eWdrCmhGZUNRL3RHSlA2RnZhN3pHZkJO
        Zi9nenZaM01wcDBSYjJVTitxTndBNm8KLS0tIHZld0plT0VOWERJQmFWU3l1ZDRJ
        WmZTWkZhVldIODM0MERoaGpJak9LakUKn29YWRu9ReqnEuaa1U6vkGUdsVNPB3st
        Q3QXJIKf2exkryL3UoN4oLGo6oYpmpGFpPs5VA+GlXc4LaLm7t7yUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-22T21:12:35Z"
  mac: ENC[AES256_GCM,data:A4UT/64vswV7gbDTEof8Ih+yKfRIHaFfD+6IsLCKxQ5NexwPEI/sbjX0FNotiLekCq3/FNyASh/R8cCgNYeoMf0HowJOdqwHAs2PVBZ91uvQhdz9E/xhvola6WoL5p05oZIR9yp9Ue0lbB/mddfqDjem2pBR5hIL5YNnll1Ztsk=,iv:TKVMD+KusExcXGKBGsd5NCsQogKyZNTGqqbeBbjbBbk=,tag:nA4K3z3JEwsOp9CnTzg7Vw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
