apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
  namespace: tools
stringData:
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:sPkdiGOEapHjzSp7hNx7NDSb/WFJsspqxLjgWjQ60vageGXmrvgATtPvjjqvXXAsVJQ=,iv:izMdHz1UPgDjUTHcwn8gSyElH4G3hXBIYhK0fRKPJIQ=,tag:E3v0ymnmIDmi5j8MtXK4VA==,type:str]
  PAPERLESS_DBUSER: ENC[AES256_GCM,data:lNvW2sfHc6h2,iv:iV/gUuH9+nUiiPHTG0zxIFkARBAnc2O+BbtW2yYPJ0E=,tag:qOqgecnuN1sGrRgtMGwHNQ==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:VjGbpT6emvmrKNRFxAbzutOaNdNlcg+hJxoWYqBV/LA=,iv:fF1a9vyjuKC/iU9BbHAymTxS2bILQVw83MYcXHgMupA=,tag:sCc8DCYEGF+9FwtciYp4Fg==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:GwDdShI=,iv:Pw1jPm1k9le0mINdn+dYWdVjBcNnQ5RoEojCVchXbvM=,tag:/kTKvHIIuVjDBcfjp+FqfA==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:RvTbW+mBWSYlbe1vCPP1QcgGAqw=,iv:RxfkeR2R3LqJMpz9Yueg2RBzQAzwOo2udqOqHdr2C6Q=,tag:mc3liUN1H/DerKP9Ta0Qag==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:S2dFlGW3xCv9zsF0y0kw2XiYVGVQ5aithaISJffB4SbWmsO36B8tiGk=,iv:+3aDT0A3bC+L5hq1tiTGkmmiPVcrerMFp/tyomwcgiY=,tag:bu5w5bD6CYRUvoCcdWlSZw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:O0ER4NmdXfr3,iv:NINMlAC3JBoCn6F2d0MWha9WMMIjMyxwwny7Z66iC0I=,tag:iCaa1+SCvglnDvTu9zGJDQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qwls8hvyGRADWGm7R5QG/s+lrKM9u/BnhbjSR6CbDGI=,iv:7/4suR3vpTX1S65Yy13VsFVaBfvGCrIpb4FnKGBQTcU=,tag:wA/P5gRmbG03RKx4sdfcvA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:fNq5ODHXGQH9,iv:VtPDVEI1S+CAPoIGC5xEG6duGe7Ar93UrEw10n/uis0=,tag:mHtBGEd2v9bJmqm7SST20w==,type:str]
sops:
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaM2ppdUZwZWpVNGkyY3g4
        bmhsQlZoU2cyQWN4a051Mkx1bW1vTHpRU2pFCk96OW0wZEpmYXc2VTFNamMvWjh0
        cExYSmhDYkt2V2RWaWRsaHhhMU1JSUkKLS0tIDg2Y0Z6YTBpMWNOQlFnOVIwQXNZ
        amk4M3NXTnJHaGZCTGx1WjFOeUdQMUEKwf6tUFchQUuCYQ5oxufpAvnaMpWkswZV
        LSCdfn7oSN4sRjWw//IjMbt2XK5/w4DPdcr2oqrXDMGZgjwgTLyt6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-25T09:59:45Z"
  mac: ENC[AES256_GCM,data:olBta1/kQvRPAj0NmypNjEhOpU7dULmcsJX3ldwFwx7ZVlcmV1IHdqkpA8lmzVgqlLAypwvd/+pZCxYfExudom5Im3K23lhjbxWD8d2rdaKY/Oha6RElyfFzG8koFsdM71qn5VnaAgJvl4A8EzpBQKw5RbwnODuzkDm0dRrOkUQ=,iv:y5O6MeudBWbeOZSNMIlUYtAudzg+p7E8dFlXZTPnCu0=,tag:+Gr2WerhWJuVl6xGXDlsCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
