---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: healthchecks
  namespace: flux-system
spec:
  decryption:
    provider: sops
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: healthchecks
  path: "./kubernetes/apps/observability/healthchecks/app"
  prune: true
  dependsOn:
    - name: volsync
      namespace: storage
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # Default false for speed, enable for critical
  components:
    - ../../../../components/volsync-kopia
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: healthchecks
      VOLSYNC_COPYMETHOD: Direct
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_STORAGECLASS: local-path
      VOLSYNC_PUID: "1000"
      VOLSYNC_PGID: "1000"
