---
apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-config
  namespace: storage
spec:
  template:
    spec:
      containers:
        - name: configure
          image: docker.io/curlimages/curl:8.20.0@sha256:b3f1fb2a51d923260350d21b8654bbc607164a987e2f7c84a0ac199a67df812a
          command: ["/bin/sh", "/scripts/configure.sh"]
          env:
            - name: HARBOR_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-secret
                  key: HARBOR_ADMIN_PASSWORD
            - name: HARBOR_ROBOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: harbor-secret
                  key: HARBOR_ROBOT_SECRET
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: harbor-config-script
            defaultMode: 0755
      restartPolicy: OnFailure
  backoffLimit: 6
