---
apiVersion: batch/v1
kind: Job
metadata:
  name: harbor-config
  namespace: storage
spec:
  template:
    spec:
      containers:
        - name: configure
          image: docker.io/curlimages/curl:8.19.0@sha256:9a6f6a17667960e077f1b153009aaf18ac99a622221084e1938a45a06fff057a
          command: ["/bin/sh", "/scripts/configure.sh"]
          env:
            - name: HARBOR_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: harbor-secret
                  key: HARBOR_ADMIN_PASSWORD
            - name: HARBOR_ROBOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: harbor-secret
                  key: HARBOR_ROBOT_SECRET
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: scripts
          configMap:
            name: harbor-config-script
            defaultMode: 0755
      restartPolicy: OnFailure
  backoffLimit: 6
