---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tns-csi-secret
  namespace: storage
spec:
  refreshInterval: 1h
  target:
    name: tns-csi-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        url: "wss://truenas.vaderrp.com/api/current"
        api-key: "{{ .apikey }}"
  data:
    - secretKey: apikey
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 9f80ad57-19ae-49a0-be46-41ffcb668d8e
        property: apikey
