---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/fluxcd.controlplane.io/resourcesetinputprovider_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: paikky-branches
  namespace: paikky
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "1m"
spec:
  type: GiteaBranch
  url: http://192.168.7.30:3000/operinko-labs/paikky_calendar_export
  filter:
    includeBranch: "^main$"
  secretRef:
    name: paikky-forgejo-pat
