apiVersion: v1
kind: Secret
metadata:
  name: healthchecks-secret
  namespace: observability
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:fmgElF34w8KcBwi+lapMDIhlNRrnaGwzSL1p58B5a4H2+2LtgJuOOflfHC1dIg6/1RU=,iv:300tYEKeENyLxsT36bJiZYcfQiTjPDAK6ZJrVBsMw38=,tag:ZHONSSye43AvzpgAjcDKtQ==,type:str]
sops:
  age:
    - recipient: age18hklnzlqlz0y7tf8gzeh2slv8vxnlyvjcn7e38xsd744s3t9hf0su4lwpx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySnV0dk56KzhtNUVNK0JG
        THUzUUNpelJVQlFFTjBFS3N1QjBnMnlMNVJNCkwwTFk0QzRTM2lUbEVuR2dVOGEw
        MGFYRmZES09OQW9sVCtWWHBVSGZ6bTgKLS0tIHc2a0J0LzJaU0s1Rjl1YkFRSVky
        aFZBVEZSZno4Umh2czdicUczRlArencKdv/CPJ2Rt/rZEZVq5t5/mpa1Nid0Px60
        /fDVomIIxBX1CWZNbSulx0zEpYda3jXsB0plI+XjuF66ZPvREk0IGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-25T09:59:45Z"
  mac: ENC[AES256_GCM,data:XAVjtTkeV4sfi00CgAsaMngDkueSNSviJzOCTi2Cbp84dduvQcrECmXUazWPipjtgpPTp1hVS7aIGlgyhTISc2bjvLu0UNHhFgLROea0dqh66vZPYyK8Ajds9YCboAmjOzfPHrViXsdzPPsmyNYKI2Qje1+KAdsafc8z32AWBAY=,iv:O4H/nU08W2/IqfldN/as24W9LFbAGWX3zsJgVYc0r/M=,tag:sB2BkZ1XcNDz8KQWGPDGaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
